#############################################################################
# libraries to load
#############################################################################

# base packages
library('DBI')
library('dplyr')
library('tidyverse')
library('anytime')
library('here')
library('xlsx')
library('openxlsx')
library('tidyr')
library('ggplot2')
library('stringr')
library('gt')
library('haven')
library('ROracle')
library('data.table')
library('readxl')
library('formattable')
library('flexdashboard')
library('lubridate')
library('usethis')
library('gitcreds')
library('devtools')
#library('googledrive')

# lesser used (will document these)
#library('sqldf')
#library('qdap')
#library('tm')
#library('SnowballC')
#library('lubridate')
#library('ggthemes', dependencies = TRUE)
